# Generated by Django 5.0.2 on 2024-03-27 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.UUIDField(default=uuid.UUID('2af43e82-ed51-4105-8513-6a959d26e1ab'), editable=False, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('ID', 'National ID'), ('Passport', 'Passport Number'), ('Military ID', 'Military ID'), ('Alien ID', 'ALIEN ID')], max_length=100)),
                ('id_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0a4e2904-e511-4c09-b932-ca405100754b'), primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer', unique=True)),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c4d8c8e6-0414-4712-88f4-32504dc29521'), primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer')),
            ],
            options={
                'db_table': 'deposits',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('94c9ee78-d5bd-41f9-8f06-2965d3dbe4a7'), primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer')),
            ],
            options={
                'db_table': 'withdrawals',
            },
        ),
    ]
