# Generated by Django 5.0.2 on 2024-03-27 04:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd83fa91-db3e-43d8-b021-d5787a993135'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.UUIDField(default=uuid.UUID('d88509ec-9548-4e54-bdc2-ecacb89ff008'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8341e82e-426b-4474-8f76-5a83996d210c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cee6fbea-b369-4635-a4d3-d2746e5350b1'), primary_key=True, serialize=False),
        ),
    ]
